AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - './bin/*'
    - './exe/*'
    - './Rakefile'
    - './Gemfile'
    - './*.gemspec'

Metrics/BlockLength:
  Exclude:
    - './*.gemspec'

Metrics/LineLength:
  Exclude:
    - './*.gemspec'
    - 'exe/fuel_surcharge'

# Lint/AssignmentInCondition:
#   Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'
