Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - './*.gemspec'

Metrics/LineLength:
  Exclude:
    - './*.gemspec'

# Lint/AssignmentInCondition:
#   Enabled: false

# Metrics/MethodLength:
  # Exclude:

# Metrics/AbcSize:
  # Exclude:
