---
language: ruby

sudo: false

cache:
  bundler: true

dist: xenial

before_install:
  - gem update --system
  - gem install bundler
  - gem install --user-install executable-hooks

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

