---
sudo: false

dist: xenial

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

os:
  - linux
  - osx

cache:
  bundler: true

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle install
  - bundle exec rake test
