---
language: ruby
cache: bundler
dist: xenial

before_install:
  - gem update --system
  - gem install bundler
  # This is necessary to run `bundle exec rake` on Travis CI with Ruby 2.6
  - gem install --user-install executable-hooks

rvm:
  - 2.4
  - 2.5
  - 2.6
